version: "3.8"

services:
  control-api:
    build:
      context: ./control-api
    container_name: mc-control-api
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # The MC server container will be created/removed dynamically by the API using the repo's start script
  # We do not declare it statically here to allow per-repo customization.
